 name: Pull request comment

 on:
  pull_request: 
    types: [opened]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comments on new pr
        uses: actions/github-script@v7
        with:
          script: |-
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Thanks for contributing.',
            });



    