name: Container version check
on: [workflow_dispatch]

jobs: 
  check-native-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node version and OS Version on VM
        run: |-
            node -v
            cat /etc/lsb-release
      - run: echo "Sone text" > text.txt
  check-container-version:
    runs-on: ubuntu-latest
    container: 
        image: node:current-alpine3.19
    steps:
      - name: Print Node version and OS Version on Container
        run: |-
            node -v
            cat /etc/os-release
      - name: Container running in step (Print Java version)
        uses: docker://amazoncorretto:22-alpine3.20
        with:
          entrypoint: /usr/bin/java
          args: --version
      - name: Container running in step (Lof text.txt file content)
        uses: docker://amazoncorretto:22-alpine3.20
        with:
          entrypoint: cat
          args: text.txt

