name: First Github Actions Job
on: [push]
  
jobs:
  runs-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Print a simple message
        run: echo "Hi There!"
      #- name: Installing SDKMAN, JAVA AND MAVEN
       # run: |-
           # curl -s "https://get.sdkman.io" | bash
           # source "$HOME/.sdkman/bin/sdkman-init.sh"
           # sdk install java 22.0.2-amzn
            #sdk install maven
            #javac -version
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '22'
          #cache: 'maven'
      - name: Multiple Commands
        run: |-
            node -v
            npm -v
            java --version
            mvn -v
            uname -a
            cat /etc/lsb-release
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: Print Macos version
        run: sw_vers
  dependent-job-windows:
    runs-on: windows-latest
    needs: runs-shell-script
    steps:
      - name: Prints PowerShell
        run: Write-Output "Hi There!"
      - name: Prints Windows Version
        run: systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version" 

        
