name: First Github Actions Job
on: [push]
  
jobs:
  runs-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Print a simple message
        run: echo "Hi There!"
      - name: Installing SDKMAN, JAVA AND MAVEN
        run: |-
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java 22.0.2-amzn
            sdk install maven
            javac -version
      - name: Multiple Commands
        run: |-
            node -v
            npm -v
            javac --version
            mvn -v
            uname -a
            cat /etc/lsb-release
        
