name: Manually Triggered
on:
  workflow_dispatch:
    inputs:
      name:
        description: A string input
        type: string
        required: true
        default: "Default value"
      times:
        description: A number input
        default: 4
        type: number
      version:
        description: "An Options Input"
        required: true
        default: "Option 3"
        type: choice
        options:
          - Option 1
          - Option 2
          - Option 3
      run:
        description: A boolean option
        required: false
        type: boolean
      env:
        description: "Environment"
        type: environment
        required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{ inputs.name }}"
          echo "Number: ${{ inputs.times }}"
          echo "Option: ${{ inputs.version }}"
          echo "Boolean: ${{ inputs.run }}"
          echo "Environment: ${{ inputs.environment }}"