name: Using Reusable Workout
on: push

jobs:
  calling-resuable-wf:
    uses: ./.github/workflows/reusable-workflow.yaml
  using-called-wf:
    needs: calling-resuable-wf
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.calling-resuable-wf.outputs.date }}