name: Workflow Commands
on: [push]

jobs:
  GithubActions:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Mask
        run: echo "::add-mask::${{vars.PASSWORD}}"
      - name: Group Logs
        run: |-
            echo "::group::My Group"
            echo "Password: ${{vars.PASSWORD}}"
            echo "::endgroup::"


        